Tutorial on how to use syslib. Currently available: calibration feature only.

In [1]:
import numpy as np
from sysspectra import syslib as syl

Let's initiate a Calibration class and check it out 

In [2]:
calib=syl.Calibration()

In [3]:
calib

Calibration:
  cXnu1: 1.0
  cYnu2: 1.0

calib takes two input arguments. Those are supposed to be the calibration factors, one for each field X,Y and frequency nu1,nu2. E.g., calibration factor for field T measured at frequency 95GHz. 

In [5]:
calib.defaults

{'cXnu1': 1.0, 'cYnu2': 1.0}

We can change the defaults value via the set_defaults function

In [8]:
calib.set_defaults(cXnu1=3.)
calib

Calibration:
  cXnu1: 3.0
  cYnu2: 1.0

Let's now look at the output. The input arguments can be passed as two scalars. In this case, the output is a scalar.

In [4]:
calib(cXnu1=2.,cYnu2=3.)

array([6.])

Or as an array and a scalar. Note that order matters. In this case, the output is a column vector.

In [6]:
calib(cXnu1=[1.,2.])

array([[1.],
       [2.]])

In this other case, where cXnu1 is a scalar and cYnu2 is an array, the output is a row vector.

In [9]:
calib(cYnu2=[1.,2.])

array([3., 6.])

The most general case, when both cXnu1 and cYnu2 are arrays, gives a matrix as an output.

In [10]:
calib(cXnu1=[1.,2.],cYnu2=[3.,4.])

array([[3., 4.],
       [6., 8.]])

Suppose now that cT=[1,2,3] is the array of calibration factors of T maps for a set
of 3 frequencies (say, 95, 150, 220 GHz). cE=[4,5,6] is the analogue for E maps. Let's call calib() with these two input arguments.

In [12]:
cT=[1.,2.,3.]
cE=[4.,5.,6.]
calib(cXnu1=cT, cYnu2=cE)

array([[ 4.,  5.,  6.],
       [ 8., 10., 12.],
       [12., 15., 18.]])

Each entry of this matrix corresponds to the calibration factor of the TE auto- and cross-spectra.
E.g., element (0,0) is the calibration factor of the 95x95 TE spectrum.
Element (0,1) is the calibration factor of the 95x150 spectrum, i.e. T from 95 and E from 150.
Note that it is different from element (1,0), which is the cal factor for TE 150x95,
i.e. T from 150 and E from 95.